[package]
name = "hash_and_xattr"
version = "0.1.3"
edition = "2021"

[dependencies]
sha2 = "0.10"      # for SHA512 hashing
walkdir = "2.3"    # for directory traversal
xattr = "0.2"      # for interacting with extended attributes
rayon = "1.7"      # parallel processing
atty = "0.2"       # Add atty to check if stdin is connected
