[package]
name = "hash_and_xattr"
version = "0.2.0"
edition = "2021"

[dependencies]
sha2 = "0.10"      # SHA512 hashing
walkdir = "2.3"    # Directory traversal
xattr = "0.2"      # interacting with extended attributes
rayon = "1.7"      # parallel processing
atty = "0.2"       # Add atty to check if stdin is connected
openssl = "0.10"   # private/public crypto key signing
libc = "0.2"       # setxattr
